services:
  - type: web
    name: crealert-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: GREENAPI_ID
        sync: false
      - key: GREENAPI_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_PHONES
        sync: false 